### ISSUE TITLE
How to get result of test data? or what is the model's save path?

### ISSUE THREAD

**Issue by parkhy0106** [twitter-research/cwn#87]
Previously I trained the model with my own data and it looks okay. but I can't find how to get test result(not accuracy metric but the result model returns). Is there any tools? or should I make one of it?

**Comment by ayeshasiddika9196** [comment]
@twitter-service

**Comment by parkhy0106** [comment]
@twitter-research Now I found that 'run_exp.py' only save curves and doesn't save trained model and it is feels too strange for me. Is it because manually saving and loading model for infer might break whole code?

**Comment by Noired** [comment]
Hi @parkhy0106 , thanks for reaching out!

The current version of our code does not automatically save a trained model to disk to perform inference at a later stage. Please note that we have not included this simply because there has not been any need for it on our side so far, and not because this would be incompatible with our infrastructure.

In general, we appreciate that this may be a convenient feature to have, especially when running experiments outside of those considered in out papers. 

Either way, we do not envision problems arising when trying to implement the required functionalities with a standard approach as the one described for example [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html). Have you tried to implement this functionality and observed any behaviour worth reporting here?

**Comment by parkhy0106** [comment]
I actually don't have much time so didn't tried that much. but at least I can't pickle model because it's local object. But I found inference part so added my own args to inference another data locally and it works fine. That means it's possible. So is there any possibility that I can meet save load available version? I really liked this concept because I think It would have strength to MO prediction. Thanks.

**Comment by Noired** [comment]
I am not sure I understand what your current issue is at the moment.

As I said, one should follow the suggested PyTorch guidelines to save/load models:
> https://pytorch.org/tutorials/beginner/saving_loading_models.html

We will consider adding this functionality in the near future. In the meantime, I invite you to be more specific and clear to let us understand whether we are in the position to help you.

**Comment by parkhy0106** [comment]
Actually, My current issue is that I've never tried model saving and loading. 
So I can't even know whether it is possible or not. Because my environment is not in local, I currently have no permission to access it from now. I'll try your suggestion when It become possible. Thanks for your kind reply. Sincerely.
